module.exports = [
  { number: 0, type: "start", label: "START" },
  { number: 1, type: "mail", count: 1, label: "MAIL📧📬" },
  { number: 2, type: "mail", count: 2, label: "2 MAIL📧📧📬" },
  { number: 3, type: "deal", label: "DEAL" },
  { number: 4, type: "mail", count: 1, label: "MAIL📧📬" },
  { number: 5, type: "mail", count: 1, label: "MAIL📧📬" },
  { number: 6, type: "lottery", label: "LOTTERY💲🤑💲" },
  { number: 7, type: "mail", count: 1, label: "MAIL📧📬" },

  { number: 8, type: "radio", amount: 1000, label: "RADIO📻" },
  { number: 9, type: "buyer", label: "BUYER" },
  { number: 10, type: "mail", count: 2, label: "2 MAIL📧📧📬" },
  { number: 11, type: "deal", label: "DEAL" },
  { number: 12, type: "birthday", amountPerPlayer: 100, label: "BIRTHDAY🎂" },
  { number: 13, type: "mail", count: 1, label: "MAIL📧📬" },
  { number: 14, type: "lottery", label: "LOTTERY💲🤑💲" },
  { number: 15, type: "buyer", label: "BUYER👨🏿" },

  { number: 16, type: "mail", count: 3, label: "3 MAIL📧📧📧" },
  { number: 17, type: "deal", label: "DEAL🤝🏻" },
  { number: 18, type: "mail", count: 1, label: "MAIL📧📬" },
  { number: 19, type: "buyer", label: "BUYER👳🏾‍♂️‍" },
  { number: 20, type: "lottery", label: "LOTTERY💲🤑💲" },
  { number: 21, type: "ski", cost: 500, label: "TOP-GOLF⛳" },
  { number: 22, type: "mail", count: 2, label: "2 MAIL📧📧📬" },
  { number: 23, type: "deal", label: "DEAL🤝🏻" },

  { number: 24, type: "mail", count: 1, label: "MAIL📧📬" },
  { number: 25, type: "charity", cost: 1000, label: "CHARITY🧔🏾" },
  { number: 26, type: "lottery", label: "LOTTERY💲🤑💲" },
  { number: 27, type: "deal", label: "DEAL🤝🏻" },
  { number: 28, type: "buyer", label: "BUYER👳🏾‍♂️" },
  { number: 29, type: "yardsale", label: "YARD SALE" },
  { number: 30, type: "walk", label: "WALK🚶‍♀️" },
  { number: 31, type: "payday", salary: 3500, label: "PLAY-DAY💲💲💲" }
];